phraseapp:
  project_id: 0a057f486f0781e2617fde5179386ced
  push:
    sources:
    - file: ./quote/<locale_code>.lproj/Localizable.strings
      params:
        file_format: strings
        update_translations: true
  pull:
    targets:
    - file: ./quote/<locale_code>.lproj/Localizable.strings
      params:
        file_format: strings
        
